import type { Product } from "./Types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "NFC Mifare Classic Card",
    price: 12.99,
    category: "NFC",
    description: "Original 13.56MHz RFID card, perfect for collectors",
    image: "nfc",
    stock: 25,
  },
  {
    id: "2",
    name: "Bitcoin Genesis Block NFT",
    price: 299.99,
    category: "Blockchain",
    description:
      "Limited edition digital collectible commemorating Bitcoin's first block",
    image: "blockchain",
    stock: 10,
  },
  {
    id: "3",
    name: "GPT-3 Launch Token",
    price: 89.99,
    category: "AI",
    description: "Commemorative token from OpenAI's GPT-3 launch event",
    image: "ai",
    stock: 15,
  },
  {
    id: "4",
    name: "Ethereum Proof-of-Stake Pin",
    price: 45.5,
    category: "Blockchain",
    description: "Limited edition pin celebrating The Merge to PoS",
    image: "blockchain",
    stock: 30,
  },
  {
    id: "5",
    name: "NFC Ring Gen 1",
    price: 67.0,
    category: "NFC",
    description: "First generation NFC smart ring, rare collector's item",
    image: "nfc",
    stock: 8,
  },
  {
    id: "6",
    name: "Neural Network Chip Prototype",
    price: 199.99,
    category: "AI",
    description: "Early prototype of dedicated AI inference chip",
    image: "ai",
    stock: 5,
  },
  {
    id: "7",
    name: "Lightning Network Node Badge",
    price: 34.99,
    category: "Blockchain",
    description: "Official badge for early Lightning Network node operators",
    image: "blockchain",
    stock: 20,
  },
  {
    id: "8",
    name: "RFID Implant Kit v1.0",
    price: 149.99,
    category: "NFC",
    description: "Original RFID biohacking implant kit, sealed",
    image: "nfc",
    stock: 3,
  },
  {
    id: "9",
    name: "AlphaGo Victory Commemorative",
    price: 129.99,
    category: "AI",
    description:
      "Limited edition piece from DeepMind's historic AlphaGo victory",
    image: "ai",
    stock: 12,
  },
  {
    id: "10",
    name: "Smart Contract Ledger",
    price: 78.99,
    category: "Blockchain",
    description:
      "Physical ledger containing first 1000 smart contracts on Ethereum",
    image: "blockchain",
    stock: 18,
  },
  {
    id: "11",
    name: "Quantum Computing Demo Chip",
    price: 499.99,
    category: "Quantum",
    description: "Decommissioned quantum qubit demonstration chip",
    image: "quantum",
    stock: 2,
  },
  {
    id: "12",
    name: "IoT Sensor Array v1",
    price: 54.99,
    category: "IoT",
    description: "First generation IoT environmental sensor array",
    image: "iot",
    stock: 22,
  },
];
